/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.runelite.mapping.Export
 *  net.runelite.mapping.Implements
 *  net.runelite.mapping.ObfuscatedGetter
 *  net.runelite.mapping.ObfuscatedName
 *  net.runelite.mapping.ObfuscatedSignature
 */
import net.runelite.mapping.Export;
import net.runelite.mapping.Implements;
import net.runelite.mapping.ObfuscatedGetter;
import net.runelite.mapping.ObfuscatedName;
import net.runelite.mapping.ObfuscatedSignature;

@ObfuscatedName(value="mn")
@Implements(value="ServerPacket")
public class ServerPacket {
    @ObfuscatedName(value="ay")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3468 = new ServerPacket(0, -1);
    @ObfuscatedName(value="ah")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3444 = new ServerPacket(1, 7);
    @ObfuscatedName(value="az")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3445 = new ServerPacket(2, 6);
    @ObfuscatedName(value="ao")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3446 = new ServerPacket(3, 12);
    @ObfuscatedName(value="ad")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3535 = new ServerPacket(4, 8);
    @ObfuscatedName(value="an")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3460 = new ServerPacket(5, 6);
    @ObfuscatedName(value="ae")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3497 = new ServerPacket(6, 5);
    @ObfuscatedName(value="ax")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3519 = new ServerPacket(7, 4);
    @ObfuscatedName(value="at")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3451 = new ServerPacket(8, 2);
    @ObfuscatedName(value="ac")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3452 = new ServerPacket(9, 10);
    @ObfuscatedName(value="au")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3516 = new ServerPacket(10, 2);
    @ObfuscatedName(value="as")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3474 = new ServerPacket(11, 8);
    @ObfuscatedName(value="aq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3472 = new ServerPacket(12, -2);
    @ObfuscatedName(value="af")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3456 = new ServerPacket(13, 6);
    @ObfuscatedName(value="aa")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3457 = new ServerPacket(14, 7);
    @ObfuscatedName(value="ak")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3491 = new ServerPacket(15, -2);
    @ObfuscatedName(value="al")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3459 = new ServerPacket(16, 0);
    @ObfuscatedName(value="av")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3449 = new ServerPacket(17, -2);
    @ObfuscatedName(value="ag")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3461 = new ServerPacket(18, 2);
    @ObfuscatedName(value="aw")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3501 = new ServerPacket(19, 14);
    @ObfuscatedName(value="ai")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3463 = new ServerPacket(20, 7);
    @ObfuscatedName(value="ar")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3464 = new ServerPacket(21, -2);
    @ObfuscatedName(value="am")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3454 = new ServerPacket(22, 1);
    @ObfuscatedName(value="ap")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3466 = new ServerPacket(23, 4);
    @ObfuscatedName(value="ab")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3520 = new ServerPacket(24, -2);
    @ObfuscatedName(value="aj")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3540 = new ServerPacket(25, 8);
    @ObfuscatedName(value="bu")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3469 = new ServerPacket(26, 9);
    @ObfuscatedName(value="bh")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3470 = new ServerPacket(27, 3);
    @ObfuscatedName(value="bw")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3471 = new ServerPacket(28, 20);
    @ObfuscatedName(value="bb")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3564 = new ServerPacket(29, 7);
    @ObfuscatedName(value="bx")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3473 = new ServerPacket(30, 4);
    @ObfuscatedName(value="bd")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3562 = new ServerPacket(31, -2);
    @ObfuscatedName(value="bi")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3475 = new ServerPacket(32, 4);
    @ObfuscatedName(value="bz")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3476 = new ServerPacket(33, 8);
    @ObfuscatedName(value="bt")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3477 = new ServerPacket(34, 6);
    @ObfuscatedName(value="bf")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3478 = new ServerPacket(35, 12);
    @ObfuscatedName(value="by")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3479 = new ServerPacket(36, -1);
    @ObfuscatedName(value="bm")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3465 = new ServerPacket(37, -2);
    @ObfuscatedName(value="bp")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3487 = new ServerPacket(38, 6);
    @ObfuscatedName(value="bg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3482 = new ServerPacket(39, 5);
    @ObfuscatedName(value="bc")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3483 = new ServerPacket(40, 5);
    @ObfuscatedName(value="bv")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3467 = new ServerPacket(41, 1);
    @ObfuscatedName(value="bq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3521 = new ServerPacket(42, -1);
    @ObfuscatedName(value="ba")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3486 = new ServerPacket(43, 8);
    @ObfuscatedName(value="bk")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3485 = new ServerPacket(44, 5);
    @ObfuscatedName(value="bs")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3488 = new ServerPacket(45, 0);
    @ObfuscatedName(value="bj")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3450 = new ServerPacket(46, 4);
    @ObfuscatedName(value="bo")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3531 = new ServerPacket(47, 0);
    @ObfuscatedName(value="be")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3557 = new ServerPacket(48, -1);
    @ObfuscatedName(value="bn")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3492 = new ServerPacket(49, 2);
    @ObfuscatedName(value="br")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3493 = new ServerPacket(50, 10);
    @ObfuscatedName(value="bl")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3494 = new ServerPacket(51, 6);
    @ObfuscatedName(value="cb")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3447 = new ServerPacket(52, 9);
    @ObfuscatedName(value="cn")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3496 = new ServerPacket(53, -1);
    @ObfuscatedName(value="cc")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3481 = new ServerPacket(54, 10);
    @ObfuscatedName(value="co")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3541 = new ServerPacket(55, 0);
    @ObfuscatedName(value="ca")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3499 = new ServerPacket(56, -1);
    @ObfuscatedName(value="cg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3500 = new ServerPacket(57, 1);
    @ObfuscatedName(value="cp")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3498 = new ServerPacket(58, -2);
    @ObfuscatedName(value="cz")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3502 = new ServerPacket(59, 4);
    @ObfuscatedName(value="cy")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3503 = new ServerPacket(60, -2);
    @ObfuscatedName(value="cu")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3504 = new ServerPacket(61, 5);
    @ObfuscatedName(value="cq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3455 = new ServerPacket(62, 2);
    @ObfuscatedName(value="cf")
    @ObfuscatedSignature(descriptor="Lmn;")
    static final ServerPacket field3506 = new ServerPacket(63, -2);
    @ObfuscatedName(value="ct")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3507 = new ServerPacket(64, 20);
    @ObfuscatedName(value="ci")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3508 = new ServerPacket(65, 6);
    @ObfuscatedName(value="cl")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3509 = new ServerPacket(66, 28);
    @ObfuscatedName(value="cw")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3510 = new ServerPacket(67, 4);
    @ObfuscatedName(value="cj")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3511 = new ServerPacket(68, -2);
    @ObfuscatedName(value="cx")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3512 = new ServerPacket(69, 6);
    @ObfuscatedName(value="cd")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3513 = new ServerPacket(70, 5);
    @ObfuscatedName(value="cv")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3514 = new ServerPacket(71, 0);
    @ObfuscatedName(value="ck")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3515 = new ServerPacket(72, -1);
    @ObfuscatedName(value="cs")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3490 = new ServerPacket(73, 2);
    @ObfuscatedName(value="cm")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3517 = new ServerPacket(74, 8);
    @ObfuscatedName(value="ce")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3525 = new ServerPacket(75, -2);
    @ObfuscatedName(value="cr")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3560 = new ServerPacket(76, -2);
    @ObfuscatedName(value="ch")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3524 = new ServerPacket(77, 6);
    @ObfuscatedName(value="dh")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3462 = new ServerPacket(78, 3);
    @ObfuscatedName(value="dn")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3522 = new ServerPacket(79, 8);
    @ObfuscatedName(value="dc")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3443 = new ServerPacket(80, 6);
    @ObfuscatedName(value="dm")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3555 = new ServerPacket(81, 9);
    @ObfuscatedName(value="dj")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3518 = new ServerPacket(82, 6);
    @ObfuscatedName(value="dk")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3526 = new ServerPacket(83, -2);
    @ObfuscatedName(value="ds")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3527 = new ServerPacket(84, 4);
    @ObfuscatedName(value="dr")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3528 = new ServerPacket(85, -2);
    @ObfuscatedName(value="dl")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3529 = new ServerPacket(86, 0);
    @ObfuscatedName(value="do")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3530 = new ServerPacket(87, 7);
    @ObfuscatedName(value="dg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3579 = new ServerPacket(88, 0);
    @ObfuscatedName(value="dt")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3532 = new ServerPacket(89, 4);
    @ObfuscatedName(value="df")
    @ObfuscatedSignature(descriptor="Lmn;")
    static final ServerPacket field3533 = new ServerPacket(90, 7);
    @ObfuscatedName(value="de")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3534 = new ServerPacket(91, 0);
    @ObfuscatedName(value="dw")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3575 = new ServerPacket(92, -1);
    @ObfuscatedName(value="dv")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3536 = new ServerPacket(93, 2);
    @ObfuscatedName(value="dx")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3537 = new ServerPacket(94, 0);
    @ObfuscatedName(value="dd")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3538 = new ServerPacket(95, 4);
    @ObfuscatedName(value="dy")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3539 = new ServerPacket(96, -2);
    @ObfuscatedName(value="db")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3489 = new ServerPacket(97, 7);
    @ObfuscatedName(value="du")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3577 = new ServerPacket(98, 22);
    @ObfuscatedName(value="da")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3569 = new ServerPacket(99, 6);
    @ObfuscatedName(value="dp")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3543 = new ServerPacket(100, 2);
    @ObfuscatedName(value="di")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3544 = new ServerPacket(101, 3);
    @ObfuscatedName(value="dq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3545 = new ServerPacket(102, -2);
    @ObfuscatedName(value="dz")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3546 = new ServerPacket(103, 1);
    @ObfuscatedName(value="ex")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3547 = new ServerPacket(104, 0);
    @ObfuscatedName(value="eq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3548 = new ServerPacket(105, -2);
    @ObfuscatedName(value="ef")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3549 = new ServerPacket(106, 1);
    @ObfuscatedName(value="ei")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3550 = new ServerPacket(107, 8);
    @ObfuscatedName(value="ej")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3542 = new ServerPacket(108, 6);
    @ObfuscatedName(value="eg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3552 = new ServerPacket(109, 10);
    @ObfuscatedName(value="ek")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3553 = new ServerPacket(110, -2);
    @ObfuscatedName(value="et")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3554 = new ServerPacket(111, -2);
    @ObfuscatedName(value="ec")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3565 = new ServerPacket(112, -2);
    @ObfuscatedName(value="em")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3556 = new ServerPacket(113, 1);
    @ObfuscatedName(value="es")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3480 = new ServerPacket(114, 14);
    @ObfuscatedName(value="er")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3558 = new ServerPacket(115, -1);
    @ObfuscatedName(value="ep")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3559 = new ServerPacket(116, 3);
    @ObfuscatedName(value="eo")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3448 = new ServerPacket(117, 5);
    @ObfuscatedName(value="ez")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3561 = new ServerPacket(118, -2);
    @ObfuscatedName(value="eb")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3458 = new ServerPacket(119, 2);
    @ObfuscatedName(value="en")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3563 = new ServerPacket(120, -2);
    @ObfuscatedName(value="ee")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3551 = new ServerPacket(121, -1);
    @ObfuscatedName(value="ev")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3570 = new ServerPacket(122, 0);
    @ObfuscatedName(value="el")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3566 = new ServerPacket(123, -2);
    @ObfuscatedName(value="ea")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3567 = new ServerPacket(124, 1);
    @ObfuscatedName(value="eu")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3568 = new ServerPacket(125, 1);
    @ObfuscatedName(value="ey")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3484 = new ServerPacket(126, 11);
    @ObfuscatedName(value="eh")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3495 = new ServerPacket(127, 5);
    @ObfuscatedName(value="ew")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3571 = new ServerPacket(128, -2);
    @ObfuscatedName(value="ed")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3572 = new ServerPacket(129, -2);
    @ObfuscatedName(value="fz")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3573 = new ServerPacket(130, 4);
    @ObfuscatedName(value="fn")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3574 = new ServerPacket(131, 7);
    @ObfuscatedName(value="fd")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3523 = new ServerPacket(132, 2);
    @ObfuscatedName(value="fc")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3576 = new ServerPacket(133, -2);
    @ObfuscatedName(value="fb")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3505 = new ServerPacket(134, -2);
    @ObfuscatedName(value="fg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3578 = new ServerPacket(135, 17);
    @ObfuscatedName(value="ff")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final ServerPacket field3453 = new ServerPacket(136, 2);
    @ObfuscatedName(value="fs")
    @ObfuscatedGetter(intValue=1163003239)
    @Export(value="id")
    public final int id;
    @ObfuscatedName(value="fm")
    @ObfuscatedGetter(intValue=-315600729)
    @Export(value="length")
    public final int length;

    ServerPacket(int n, int n2) {
        this.id = n;
        this.length = n2;
    }

    @ObfuscatedName(value="an")
    @ObfuscatedSignature(descriptor="(B)V", garbageValue="42")
    public static void method6635() {
        FloorOverlayDefinition.FloorOverlayDefinition_cached.clear();
    }
}

