package old228;/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.runelite.mapping.ObfuscatedGetter
 *  net.runelite.mapping.ObfuscatedName
 *  net.runelite.mapping.ObfuscatedSignature
 */
import net.runelite.mapping.ObfuscatedGetter;
import net.runelite.mapping.ObfuscatedName;
import net.runelite.mapping.ObfuscatedSignature;

@ObfuscatedName(value="mn")
public class class325 {
    @ObfuscatedName(value="ay")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3468 = new class325(0, -1);
    @ObfuscatedName(value="ah")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3444 = new class325(1, 7);
    @ObfuscatedName(value="az")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3445 = new class325(2, 6);
    @ObfuscatedName(value="ao")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3446 = new class325(3, 12);
    @ObfuscatedName(value="ad")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3535 = new class325(4, 8);
    @ObfuscatedName(value="an")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3460 = new class325(5, 6);
    @ObfuscatedName(value="ae")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3497 = new class325(6, 5);
    @ObfuscatedName(value="ax")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3519 = new class325(7, 4);
    @ObfuscatedName(value="at")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3451 = new class325(8, 2);
    @ObfuscatedName(value="ac")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3452 = new class325(9, 10);
    @ObfuscatedName(value="au")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3516 = new class325(10, 2);
    @ObfuscatedName(value="as")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3474 = new class325(11, 8);
    @ObfuscatedName(value="aq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3472 = new class325(12, -2);
    @ObfuscatedName(value="af")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3456 = new class325(13, 6);
    @ObfuscatedName(value="aa")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3457 = new class325(14, 7);
    @ObfuscatedName(value="ak")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3491 = new class325(15, -2);
    @ObfuscatedName(value="al")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3459 = new class325(16, 0);
    @ObfuscatedName(value="av")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3449 = new class325(17, -2);
    @ObfuscatedName(value="ag")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3461 = new class325(18, 2);
    @ObfuscatedName(value="aw")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3501 = new class325(19, 14);
    @ObfuscatedName(value="ai")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3463 = new class325(20, 7);
    @ObfuscatedName(value="ar")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3464 = new class325(21, -2);
    @ObfuscatedName(value="am")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3454 = new class325(22, 1);
    @ObfuscatedName(value="ap")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3466 = new class325(23, 4);
    @ObfuscatedName(value="ab")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3520 = new class325(24, -2);
    @ObfuscatedName(value="aj")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3540 = new class325(25, 8);
    @ObfuscatedName(value="bu")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3469 = new class325(26, 9);
    @ObfuscatedName(value="bh")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3470 = new class325(27, 3);
    @ObfuscatedName(value="bw")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3471 = new class325(28, 20);
    @ObfuscatedName(value="bb")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3564 = new class325(29, 7);
    @ObfuscatedName(value="bx")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3473 = new class325(30, 4);
    @ObfuscatedName(value="bd")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3562 = new class325(31, -2);
    @ObfuscatedName(value="bi")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3475 = new class325(32, 4);
    @ObfuscatedName(value="bz")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3476 = new class325(33, 8);
    @ObfuscatedName(value="bt")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3477 = new class325(34, 6);
    @ObfuscatedName(value="bf")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3478 = new class325(35, 12);
    @ObfuscatedName(value="by")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3479 = new class325(36, -1);
    @ObfuscatedName(value="bm")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3465 = new class325(37, -2);
    @ObfuscatedName(value="bp")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3487 = new class325(38, 6);
    @ObfuscatedName(value="bg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3482 = new class325(39, 5);
    @ObfuscatedName(value="bc")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3483 = new class325(40, 5);
    @ObfuscatedName(value="bv")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3467 = new class325(41, 1);
    @ObfuscatedName(value="bq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3521 = new class325(42, -1);
    @ObfuscatedName(value="ba")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3486 = new class325(43, 8);
    @ObfuscatedName(value="bk")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3485 = new class325(44, 5);
    @ObfuscatedName(value="bs")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3488 = new class325(45, 0);
    @ObfuscatedName(value="bj")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3450 = new class325(46, 4);
    @ObfuscatedName(value="bo")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3531 = new class325(47, 0);
    @ObfuscatedName(value="be")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3557 = new class325(48, -1);
    @ObfuscatedName(value="bn")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3492 = new class325(49, 2);
    @ObfuscatedName(value="br")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3493 = new class325(50, 10);
    @ObfuscatedName(value="bl")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3494 = new class325(51, 6);
    @ObfuscatedName(value="cb")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3447 = new class325(52, 9);
    @ObfuscatedName(value="cn")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3496 = new class325(53, -1);
    @ObfuscatedName(value="cc")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3481 = new class325(54, 10);
    @ObfuscatedName(value="co")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3541 = new class325(55, 0);
    @ObfuscatedName(value="ca")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3499 = new class325(56, -1);
    @ObfuscatedName(value="cg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3500 = new class325(57, 1);
    @ObfuscatedName(value="cp")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3498 = new class325(58, -2);
    @ObfuscatedName(value="cz")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3502 = new class325(59, 4);
    @ObfuscatedName(value="cy")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3503 = new class325(60, -2);
    @ObfuscatedName(value="cu")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3504 = new class325(61, 5);
    @ObfuscatedName(value="cq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3455 = new class325(62, 2);
    @ObfuscatedName(value="cf")
    @ObfuscatedSignature(descriptor="Lmn;")
    static final class325 field3506 = new class325(63, -2);
    @ObfuscatedName(value="ct")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3507 = new class325(64, 20);
    @ObfuscatedName(value="ci")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3508 = new class325(65, 6);
    @ObfuscatedName(value="cl")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3509 = new class325(66, 28);
    @ObfuscatedName(value="cw")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3510 = new class325(67, 4);
    @ObfuscatedName(value="cj")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3511 = new class325(68, -2);
    @ObfuscatedName(value="cx")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3512 = new class325(69, 6);
    @ObfuscatedName(value="cd")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3513 = new class325(70, 5);
    @ObfuscatedName(value="cv")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3514 = new class325(71, 0);
    @ObfuscatedName(value="ck")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3515 = new class325(72, -1);
    @ObfuscatedName(value="cs")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3490 = new class325(73, 2);
    @ObfuscatedName(value="cm")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3517 = new class325(74, 8);
    @ObfuscatedName(value="ce")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3525 = new class325(75, -2);
    @ObfuscatedName(value="cr")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3560 = new class325(76, -2);
    @ObfuscatedName(value="ch")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3524 = new class325(77, 6);
    @ObfuscatedName(value="dh")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3462 = new class325(78, 3);
    @ObfuscatedName(value="dn")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3522 = new class325(79, 8);
    @ObfuscatedName(value="dc")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3443 = new class325(80, 6);
    @ObfuscatedName(value="dm")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3555 = new class325(81, 9);
    @ObfuscatedName(value="dj")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3518 = new class325(82, 6);
    @ObfuscatedName(value="dk")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3526 = new class325(83, -2);
    @ObfuscatedName(value="ds")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3527 = new class325(84, 4);
    @ObfuscatedName(value="dr")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3528 = new class325(85, -2);
    @ObfuscatedName(value="dl")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3529 = new class325(86, 0);
    @ObfuscatedName(value="do")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3530 = new class325(87, 7);
    @ObfuscatedName(value="dg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3579 = new class325(88, 0);
    @ObfuscatedName(value="dt")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3532 = new class325(89, 4);
    @ObfuscatedName(value="df")
    @ObfuscatedSignature(descriptor="Lmn;")
    static final class325 field3533 = new class325(90, 7);
    @ObfuscatedName(value="de")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3534 = new class325(91, 0);
    @ObfuscatedName(value="dw")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3575 = new class325(92, -1);
    @ObfuscatedName(value="dv")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3536 = new class325(93, 2);
    @ObfuscatedName(value="dx")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3537 = new class325(94, 0);
    @ObfuscatedName(value="dd")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3538 = new class325(95, 4);
    @ObfuscatedName(value="dy")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3539 = new class325(96, -2);
    @ObfuscatedName(value="db")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3489 = new class325(97, 7);
    @ObfuscatedName(value="du")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3577 = new class325(98, 22);
    @ObfuscatedName(value="da")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3569 = new class325(99, 6);
    @ObfuscatedName(value="dp")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3543 = new class325(100, 2);
    @ObfuscatedName(value="di")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3544 = new class325(101, 3);
    @ObfuscatedName(value="dq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3545 = new class325(102, -2);
    @ObfuscatedName(value="dz")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3546 = new class325(103, 1);
    @ObfuscatedName(value="ex")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3547 = new class325(104, 0);
    @ObfuscatedName(value="eq")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3548 = new class325(105, -2);
    @ObfuscatedName(value="ef")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3549 = new class325(106, 1);
    @ObfuscatedName(value="ei")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3550 = new class325(107, 8);
    @ObfuscatedName(value="ej")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3542 = new class325(108, 6);
    @ObfuscatedName(value="eg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3552 = new class325(109, 10);
    @ObfuscatedName(value="ek")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3553 = new class325(110, -2);
    @ObfuscatedName(value="et")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3554 = new class325(111, -2);
    @ObfuscatedName(value="ec")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3565 = new class325(112, -2);
    @ObfuscatedName(value="em")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3556 = new class325(113, 1);
    @ObfuscatedName(value="es")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3480 = new class325(114, 14);
    @ObfuscatedName(value="er")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3558 = new class325(115, -1);
    @ObfuscatedName(value="ep")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3559 = new class325(116, 3);
    @ObfuscatedName(value="eo")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3448 = new class325(117, 5);
    @ObfuscatedName(value="ez")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3561 = new class325(118, -2);
    @ObfuscatedName(value="eb")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3458 = new class325(119, 2);
    @ObfuscatedName(value="en")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3563 = new class325(120, -2);
    @ObfuscatedName(value="ee")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3551 = new class325(121, -1);
    @ObfuscatedName(value="ev")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3570 = new class325(122, 0);
    @ObfuscatedName(value="el")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3566 = new class325(123, -2);
    @ObfuscatedName(value="ea")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3567 = new class325(124, 1);
    @ObfuscatedName(value="eu")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3568 = new class325(125, 1);
    @ObfuscatedName(value="ey")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3484 = new class325(126, 11);
    @ObfuscatedName(value="eh")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3495 = new class325(127, 5);
    @ObfuscatedName(value="ew")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3571 = new class325(128, -2);
    @ObfuscatedName(value="ed")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3572 = new class325(129, -2);
    @ObfuscatedName(value="fz")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3573 = new class325(130, 4);
    @ObfuscatedName(value="fn")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3574 = new class325(131, 7);
    @ObfuscatedName(value="fd")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3523 = new class325(132, 2);
    @ObfuscatedName(value="fc")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3576 = new class325(133, -2);
    @ObfuscatedName(value="fb")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3505 = new class325(134, -2);
    @ObfuscatedName(value="fg")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3578 = new class325(135, 17);
    @ObfuscatedName(value="ff")
    @ObfuscatedSignature(descriptor="Lmn;")
    public static final class325 field3453 = new class325(136, 2);
    @ObfuscatedName(value="fs")
    @ObfuscatedGetter(intValue=1163003239)
    public final int field3580;
    @ObfuscatedName(value="fm")
    @ObfuscatedGetter(intValue=-315600729)
    public final int field3581;

    class325(int n, int n2) {
        this.field3580 = n;
        this.field3581 = n2;
    }

    @ObfuscatedName(value="an")
    @ObfuscatedSignature(descriptor="(B)V", garbageValue="42")
    public static void method6635() {
        OverlayDef.field2914.method6581();
    }
}

